[tool.black]
target-version = ["py39"]

[tool.isort]
profile = "black"
force_sort_within_sections = true
include_trailing_comma = true
line_length = 79

[tool.pyright]
exclude = [".vscode/stubs", "venv"]
pythonVersion = "3.9"
typeCheckingMode = "strict"
reportUnknownMemberType = false
reportMissingTypeStubs = false
