[tool.poetry]
name = "flow"
version = "0.0.6"
description = "Lambda app for reposting posts from VK to Telegram"
authors = ["Lev Vereshchagin <mail@vrslev.com>"]
repository = "https://github.com/vrslev/flow"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
sqlmodel = "^0.0.5"
requests = "^2.26.0"
base-telegram-bot = {git = "https://github.com/vrslev/base-telegram-bot.git", rev = "main"}
base-vk-api = {git = "https://github.com/vrslev/base-vk-api.git", rev = "main"}
python-dotenv = "^0.19.2"
boto3 = "^1.20.26"
boto3-stubs = {extras = ["s3"], version = "^1.20.26"}
sentry-sdk = "^1.5.1"
pytest = {version = "6.2.5", optional = true}
pytest-cov = {version = "3.0.0", optional = true}
pytest-randomly = {version = "3.10.3", optional = true}
responses = {version = "0.16.0", optional = true}

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pre-commit = "^2.15.0"

[tool.poetry.extras]
test = ["pytest", "pytest-cov", "pytest-randomly", "responses"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ["py39"]

[tool.isort]
profile = "black"

[tool.pyright]
typeCheckingMode = "strict"
pythonVersion = "3.9"
reportPrivateUsage = false

[tool.coverage.report]
skip_covered = true
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "if __name__ == \"__main__\":",
]
